# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtorient.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qtorient(object):
    def setupUi(self, qtorient):
        qtorient.setObjectName("qtorient")
        qtorient.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(qtorient)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(qtorient)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(qtorient)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.accel_y = QtWidgets.QLineEdit(qtorient)
        self.accel_y.setEnabled(True)
        self.accel_y.setAcceptDrops(False)
        self.accel_y.setReadOnly(True)
        self.accel_y.setObjectName("accel_y")
        self.gridLayout_2.addWidget(self.accel_y, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(qtorient)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 1, 1, 1)
        self.modeBox = QtWidgets.QComboBox(qtorient)
        self.modeBox.setObjectName("modeBox")
        self.gridLayout_2.addWidget(self.modeBox, 4, 2, 1, 1)
        self.pollEdit = QtWidgets.QLineEdit(qtorient)
        self.pollEdit.setObjectName("pollEdit")
        self.gridLayout_2.addWidget(self.pollEdit, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(qtorient)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.incl_x = QtWidgets.QLineEdit(qtorient)
        self.incl_x.setEnabled(True)
        self.incl_x.setAcceptDrops(False)
        self.incl_x.setReadOnly(True)
        self.incl_x.setObjectName("incl_x")
        self.gridLayout_2.addWidget(self.incl_x, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(qtorient)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(qtorient)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(qtorient)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 1, 1, 1)
        self.incl_y = QtWidgets.QLineEdit(qtorient)
        self.incl_y.setEnabled(True)
        self.incl_y.setAcceptDrops(False)
        self.incl_y.setReadOnly(True)
        self.incl_y.setObjectName("incl_y")
        self.gridLayout_2.addWidget(self.incl_y, 2, 1, 1, 1)
        self.accel_x = QtWidgets.QLineEdit(qtorient)
        self.accel_x.setEnabled(True)
        self.accel_x.setAcceptDrops(False)
        self.accel_x.setReadOnly(True)
        self.accel_x.setObjectName("accel_x")
        self.gridLayout_2.addWidget(self.accel_x, 1, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(qtorient)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 8, 2, 1, 1)
        self.incl_z = QtWidgets.QLineEdit(qtorient)
        self.incl_z.setEnabled(True)
        self.incl_z.setAcceptDrops(False)
        self.incl_z.setReadOnly(True)
        self.incl_z.setObjectName("incl_z")
        self.gridLayout_2.addWidget(self.incl_z, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(qtorient)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 1, 1, 1)
        self.orientBox = QtWidgets.QComboBox(qtorient)
        self.orientBox.setObjectName("orientBox")
        self.gridLayout_2.addWidget(self.orientBox, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 1, 1, 1)

        self.retranslateUi(qtorient)
        QtCore.QMetaObject.connectSlotsByName(qtorient)

    def retranslateUi(self, qtorient):
        _translate = QtCore.QCoreApplication.translate
        qtorient.setWindowTitle(_translate("qtorient", "qtOrient"))
        self.label.setText(_translate("qtorient", "Accelerometer"))
        self.label_4.setText(_translate("qtorient", "Y"))
        self.label_8.setText(_translate("qtorient", "Poll period"))
        self.label_2.setText(_translate("qtorient", "Inclination"))
        self.label_3.setText(_translate("qtorient", "X"))
        self.label_5.setText(_translate("qtorient", "Z"))
        self.label_7.setText(_translate("qtorient", "Orientation"))
        self.label_6.setText(_translate("qtorient", "Mode"))
